apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: a1-git1
  project: giri-nov
spec:
  artifact:
    path:
      name: namespace-manifest/ns.yaml
    repository: giri-apr
    revision: main
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-apr5
  resourceQuotas: {}
