apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: new
  project: giri-nov
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/new/redis-15.6.4.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: new
  placement:
    selector: rafay.dev/clusterName=giri-mar4
  version: new-v2-202403051008580000
