apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: nginx-new
  project: giri-nov
spec:
  artifact:
    artifact:
      chartPath:
        name: file://artifacts/nginx-new/nginx1-0.1.0.tgz
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
  namespace: new-nginx
  placement:
    selector: rafay.dev/clusterName=giri-qc-mar26
  version: nginx-new-v1-202403270822000000
