apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qa-automation-applications
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCDmUDt0joHrI/ElLwMxqodt5xQRPNLbdPL6wKKszX1M3OEvJD/0wWKeNJx6UyG2jaQxCEMdT8sMrC2WqWJcIaRMB8KU0ZY6wv1iMO/Irj9rRFtQDl6JIpsE7R02GK4E4gUES9dD3kkH/lS2GFS97lrvxOazIpyRvhJdgLUneaT6lEX2E5jN5/ReQJvw5/kTySDgMMi6t+s6StEvE+Y54aUIplpN/atDIFFpF0SwByuuvi4q79mrlZ5hJy5EXsrm/tb0XTO+Iz9ZFMw4n+A8mioCZNEWOs/0H3eN5+fWv2YqI1dVGsmDsnxfwRr/JoYiudSOVE7XAaxkZdXlc/+SkprE5MWscdt60JaPpiVZvaX7J0gBGd6kOOy4TAhhjFQd4mI2Te056bmq21WtcyHOpYwvYntu9Cvf3M=
  template:
    metadata:
      creationTimestamp: null
      name: qa-automation-applications
      namespace: default

