apiVersion: infra.k8smgmt.io/v3
kind: AddonOverride
metadata:
  labels:
    rafay.dev/overrideScope: clusterLabels
    rafay.dev/overrideType: valuesFile
  name: addon-over
  project: giri-nov
spec:
  resource:
    type: Addon
  type: Helm
