apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: giri-qc-feb
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBJQnty8/UUOdj255IrXVLW7GWJ29SlkUv8zSsUske7qXziZyeVLGU9YXoATLC/sJwrcsIO3SPa1U1lIiugtCPF4H0MGZckcFDzxS+pbe67hnxJWYCK45Z0gC/3nhUdjL/3W3bWBVsOdHUqWpK20nyyglUoj4mL1RKf2SY8lleZO3SZPRnDRZue2kkuTJXYV+S8G1XzzOIQxQaL7A6OU19uPsn11Y0FnzsihRQC95fsBqjCQm1CuF+MDIsPyFpcQMV9kCm3IhNbD+ZqV7cJ8Bnd0eeL2Q1Dk8yxErHfF09Sv0TvLUgAkXnOinsl/ExRYi8QH3pc1r2UyU8u/zEOThWP14sUCdVYPDZakTQbvViTgdQ0aeD5+caq8+D4duKUC3NIEfcQ6jKkbxbX7MwrDAcXLh+MC0LBPFE=
  template:
    metadata:
      creationTimestamp: null
      name: giri-qc-feb
      namespace: default

