apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: giri-fleet
  project: giri-apr
spec:
  base:
    name: default-aks
    version: 2.7.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  placement:
    autoPublish: true
    fleetValues:
    - value1
    - value2
    - value3
  type: custom
  version: v2
