apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: giri-custom-cost-blueprint
  project: giri-apr
spec:
  base:
    name: default-aks
    version: 2.7.0
  costProfile:
    name: giri-aks
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: v0
