apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  labels:
    app: nginx
  name: nginx-catalog
  project: giri-apr
spec:
  artifact:
    artifact:
      catalog: default-bitnami
      chartName: nginx
      chartVersion: 16.0.2
    type: Helm
  namespace: catalog-nginx
  sharing: {}
  version: v8
