apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: repo-test
  description: repo-test
  name: ns-repo
  project: giri-apr
spec:
  artifact:
    path:
      name: ns-repo.yaml
    repository: giri-hub
    revision: main
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-apr10
  resourceQuotas: {}
