apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: system-test
  project: giri-apr
spec:
  artifact:
    path:
      name: file://system-test/system-test.yaml
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-apr10
  resourceQuotas: {}
