apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: apr-bp-managed3
  project: giri-nov
spec:
  base:
    name: default-aks
    version: 2.6.0
  customAddons:
  - name: nginx1
    version: version1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      metricsServer:
        customizationEnabled: true
      prometheusAdapter:
        customizationEnabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  type: custom
  version: v1
