apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: drift
  project: giri-nov
spec:
  base:
    name: minimal
    version: 2.5.0
  customAddons:
  - name: d1-addon
    version: v1
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  type: custom
  version: block
