apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: giri-custom-blueprint
  project: giri-nov
spec:
  base:
    name: default
    version: 2.5.0
  defaultAddons:
    csiSecretStoreConfig:
      enableSecretRotation: true
      providers:
        aws: true
      rotationPollInterval: 2m
      syncSecrets: true
    enableCsiSecretStore: true
    enableIngress: true
    enableMonitoring: true
    monitoring:
      helmExporter:
        enabled: true
      kubeStateMetrics:
        enabled: true
      metricsServer:
        enabled: true
      nodeExporter:
        enabled: true
      prometheusAdapter:
        enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  type: custom
  version: v1
