apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: BP Fleet v2 cases
  name: giri-apr5
  project: giri-nov
spec:
  base:
    name: default
    version: 2.6.0
  customAddons:
  - name: nginx1
    version: krishna-version1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      helmExporter:
        enabled: true
      kubeStateMetrics:
        enabled: true
      metricsServer:
        enabled: true
      nodeExporter:
        enabled: true
      prometheusAdapter:
        enabled: true
      resources: {}
  driftWebhook:
    enabled: true
  placement:
    autoPublish: true
    fleetValues:
    - giri5
  type: custom
  version: new-version1
