apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: incorrect-version
  project: giri-nov
spec:
  base:
    name: minimal
    version: 2.5.0
  customAddons:
  - name: wrong-addon
    version: v1
  driftWebhook:
    enabled: true
  type: custom
  version: v1
