apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: nginx11
  project: giri-nov
spec:
  base:
    name: default
    version: 2.6.0
  customAddons:
  - name: nginx11
    version: version1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v111
