apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: nginx-bp
  project: giri-nov
spec:
  base:
    name: minimal
    version: 2.5.0
  customAddons:
  - name: nginx-deployment
    version: v1
  driftWebhook:
    enabled: true
  type: custom
  version: v1
