apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: swagger
  project: giri-nov
spec:
  base:
    name: default
    version: 2.6.0
  customAddons:
  - name: nginx1
    version: version1
  defaultAddons:
    enableIngress: true
    enableVM: true
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  sharing:
    enabled: true
    projects:
    - name: giri-np
  type: custom
  version: v1
