apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: wrong-bp
  project: giri-nov
spec:
  base:
    name: default
    version: 2.5.0
  customAddons:
  - name: wrong-addon1
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
  driftWebhook:
    enabled: true
  type: custom
  version: v1
