apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: giri-hub
  project: giri-nov
spec:
  agents:
  - {}
  credentials:
    password: sealed://credentials.password
    username: giri-rafay
  endpoint: https://github.com/giri-rafay/giri-hub.git
  options:
    provider: Github
  secret:
    name: file://artifacts/giri-hub/sealed-secret.yaml
  type: Git
status:
  projects:
  - projectId: kr993wk
    repositoryId: kzlvvv2
  webhookConfig:
    webhookSecret: 5e43b5bce7227f7ceaa8406a6d12138900df37183a9abc3adf36b843b453e010
    webhookURL: https://qc-console.stage.rafay.dev/v2/config/webhook/repository/kzlvvv2
