apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: qa-automation-aplication
  project: giri-nov
spec:
  agents:
  - {}
  credentials:
    password: sealed://credentials.password
    username: giri-rafay
  endpoint: https://github.com/RafaySystems/qa-automation-applications.git
  options:
    provider: Github
  secret:
    name: file://artifacts/qa-automation-aplication/sealed-secret.yaml
  type: Git
status:
  projects:
  - projectId: kr993wk
    repositoryId: 288yre2
  webhookConfig:
    webhookSecret: 6733c6a298b5e5a28cefcfad434d8b909361202c0248f610d955736ded8aaadd
    webhookURL: https://qc-console.stage.rafay.dev/v2/config/webhook/repository/288yre2
